select 'copy ' || 'integrityeventhistory' as action;
copy integrityeventhistory FROM 'D:\Backup\flatfile\integrityeventhistory.csv';
select 'copy ' || 'nsxmanagers' as action;
copy nsxmanagers FROM 'D:\Backup\flatfile\nsxmanagers.csv';
select 'copy ' || 'hostnsxsecuritygroups' as action;
copy hostnsxsecuritygroups FROM 'D:\Backup\flatfile\hostnsxsecuritygroups.csv';
select 'copy ' || 'suspiciousfilescanreports' as action;
copy suspiciousfilescanreports FROM 'D:\Backup\flatfile\suspiciousfilescanreports.csv';
select 'copy ' || 'payloadfilter2metadatas' as action;
copy payloadfilter2metadatas FROM 'D:\Backup\flatfile\payloadfilter2metadatas.csv';
select 'copy ' || 'vulnerabilitypayloadfilter2s' as action;
copy vulnerabilitypayloadfilter2s FROM 'D:\Backup\flatfile\vulnerabilitypayloadfilter2s.csv';
select 'copy ' || 'antimalwareeventhistory' as action;
copy antimalwareeventhistory FROM 'D:\Backup\flatfile\antimalwareeventhistory.csv';
select 'copy ' || 'securityprofilemigrationtasks' as action;
copy securityprofilemigrationtasks FROM 'D:\Backup\flatfile\securityprofilemigrationtasks.csv';
select 'copy ' || 'administratorsettingvalues' as action;
copy administratorsettingvalues FROM 'D:\Backup\flatfile\administratorsettingvalues.csv';
select 'copy ' || 'suspiciousobjects' as action;
copy suspiciousobjects FROM 'D:\Backup\flatfile\suspiciousobjects.csv';
select 'copy ' || 'stagedrolloutrings' as action;
copy stagedrolloutrings FROM 'D:\Backup\flatfile\stagedrolloutrings.csv';
select 'copy ' || 'hostrecostores' as action;
copy hostrecostores FROM 'D:\Backup\flatfile\hostrecostores.csv';
select 'copy ' || 'securityprofileconnectiontypeinterfacetypes' as action;
copy securityprofileconnectiontypeinterfacetypes FROM 'D:\Backup\flatfile\securityprofileconnectiontypeinterfacetypes.csv';
select 'copy ' || 'connectiontypeoverrides' as action;
copy connectiontypeoverrides FROM 'D:\Backup\flatfile\connectiontypeoverrides.csv';
select 'copy ' || 'servicegateways' as action;
copy servicegateways FROM 'D:\Backup\flatfile\servicegateways.csv';
select 'copy ' || 'integrityrulemetadatas' as action;
copy integrityrulemetadatas FROM 'D:\Backup\flatfile\integrityrulemetadatas.csv';
select 'copy ' || 'tlsservercredentials' as action;
copy tlsservercredentials FROM 'D:\Backup\flatfile\tlsservercredentials.csv';
select 'copy ' || 'sslcertificates' as action;
copy sslcertificates FROM 'D:\Backup\flatfile\sslcertificates.csv';
select 'copy ' || 'webreputationeventhistory' as action;
copy webreputationeventhistory FROM 'D:\Backup\flatfile\webreputationeventhistory.csv';
select 'copy ' || 'hostscans' as action;
copy hostscans FROM 'D:\Backup\flatfile\hostscans.csv';
select 'copy ' || 'integrityruleoverrides' as action;
copy integrityruleoverrides FROM 'D:\Backup\flatfile\integrityruleoverrides.csv';
select 'copy ' || 'vcenterclusterinfosecurityprofilecaches' as action;
copy vcenterclusterinfosecurityprofilecaches FROM 'D:\Backup\flatfile\vcenterclusterinfosecurityprofilecaches.csv';
select 'copy ' || 'securityprofilepacketfilters' as action;
copy securityprofilepacketfilters FROM 'D:\Backup\flatfile\securityprofilepacketfilters.csv';
select 'copy ' || 'ssogroups' as action;
copy ssogroups FROM 'D:\Backup\flatfile\ssogroups.csv';
select 'copy ' || 'alert2administrators' as action;
copy alert2administrators FROM 'D:\Backup\flatfile\alert2administrators.csv';
select 'copy ' || 'hostapplianceinfos' as action;
copy hostapplianceinfos FROM 'D:\Backup\flatfile\hostapplianceinfos.csv';
select 'copy ' || 'hostsystemsettings' as action;
copy hostsystemsettings FROM 'D:\Backup\flatfile\hostsystemsettings.csv';
select 'copy ' || 'connectiontypemetadatas' as action;
copy connectiontypemetadatas FROM 'D:\Backup\flatfile\connectiontypemetadatas.csv';
select 'copy ' || 'syslogconfigurations' as action;
copy syslogconfigurations FROM 'D:\Backup\flatfile\syslogconfigurations.csv';
select 'copy ' || 'hostAntiMalware' as action;
copy hostAntiMalware FROM 'D:\Backup\flatfile\hostAntiMalware.csv';
select 'copy ' || 'securityprofilepayloadfilter2s' as action;
copy securityprofilepayloadfilter2s FROM 'D:\Backup\flatfile\securityprofilepayloadfilter2s.csv';
select 'copy ' || 'securityprofileintegrityrules' as action;
copy securityprofileintegrityrules FROM 'D:\Backup\flatfile\securityprofileintegrityrules.csv';
select 'copy ' || 'virtualrehometasks' as action;
copy virtualrehometasks FROM 'D:\Backup\flatfile\virtualrehometasks.csv';
select 'copy ' || 'alert2hostgroups' as action;
copy alert2hostgroups FROM 'D:\Backup\flatfile\alert2hostgroups.csv';
select 'copy ' || 'hostconnectiontypes' as action;
copy hostconnectiontypes FROM 'D:\Backup\flatfile\hostconnectiontypes.csv';
select 'copy ' || 'systemsettings' as action;
copy systemsettings FROM 'D:\Backup\flatfile\systemsettings.csv';
select 'copy ' || 'hostcachehmdqueries' as action;
copy hostcachehmdqueries FROM 'D:\Backup\flatfile\hostcachehmdqueries.csv';
select 'copy ' || 'virtualhostmetadatas' as action;
copy virtualhostmetadatas FROM 'D:\Backup\flatfile\virtualhostmetadatas.csv';
select 'copy ' || 'alert2network' as action;
copy alert2network FROM 'D:\Backup\flatfile\alert2network.csv';
select 'copy ' || 'systemversions' as action;
copy systemversions FROM 'D:\Backup\flatfile\systemversions.csv';
select 'copy ' || 'supersededentitys' as action;
copy supersededentitys FROM 'D:\Backup\flatfile\supersededentitys.csv';
select 'copy ' || 'alert2syslogconfigurations' as action;
copy alert2syslogconfigurations FROM 'D:\Backup\flatfile\alert2syslogconfigurations.csv';
select 'copy ' || 'hostconnectiontypeportoverrides' as action;
copy hostconnectiontypeportoverrides FROM 'D:\Backup\flatfile\hostconnectiontypeportoverrides.csv';
select 'copy ' || 'hostsummaries2' as action;
copy hostsummaries2 FROM 'D:\Backup\flatfile\hostsummaries2.csv';
select 'copy ' || 'tags' as action;
copy tags FROM 'D:\Backup\flatfile\tags.csv';
select 'copy ' || 'workloadsecuritylinks' as action;
copy workloadsecuritylinks FROM 'D:\Backup\flatfile\workloadsecuritylinks.csv';
select 'copy ' || 'alert2integrityrules' as action;
copy alert2integrityrules FROM 'D:\Backup\flatfile\alert2integrityrules.csv';
select 'copy ' || 'connectorlocks' as action;
copy connectorlocks FROM 'D:\Backup\flatfile\connectorlocks.csv';
select 'copy ' || 'amazonvpcs' as action;
copy amazonvpcs FROM 'D:\Backup\flatfile\amazonvpcs.csv';
select 'copy ' || 'tagsets' as action;
copy tagsets FROM 'D:\Backup\flatfile\tagsets.csv';
select 'copy ' || 'relaylisthosts' as action;
copy relaylisthosts FROM 'D:\Backup\flatfile\relaylisthosts.csv';
select 'copy ' || 'hostinterfaceconnectiontypes' as action;
copy hostinterfaceconnectiontypes FROM 'D:\Backup\flatfile\hostinterfaceconnectiontypes.csv';
select 'copy ' || 'connectorjobs' as action;
copy connectorjobs FROM 'D:\Backup\flatfile\connectorjobs.csv';
select 'copy ' || 'countermatchnetworks' as action;
copy countermatchnetworks FROM 'D:\Backup\flatfile\countermatchnetworks.csv';
select 'copy ' || 'temporarypasswords' as action;
copy temporarypasswords FROM 'D:\Backup\flatfile\temporarypasswords.csv';
select 'copy ' || 'countermatchintegrityrules' as action;
copy countermatchintegrityrules FROM 'D:\Backup\flatfile\countermatchintegrityrules.csv';
select 'copy ' || 'googleconnectors' as action;
copy googleconnectors FROM 'D:\Backup\flatfile\googleconnectors.csv';
select 'copy ' || 'tenanttemplate' as action;
copy tenanttemplate FROM 'D:\Backup\flatfile\tenanttemplate.csv';
select 'copy ' || 'scheduledtasks' as action;
copy scheduledtasks FROM 'D:\Backup\flatfile\scheduledtasks.csv';
select 'copy ' || 'hostinterfacestatefulfilters' as action;
copy hostinterfacestatefulfilters FROM 'D:\Backup\flatfile\hostinterfacestatefulfilters.csv';
select 'copy ' || 'securityprofileantimalware' as action;
copy securityprofileantimalware FROM 'D:\Backup\flatfile\securityprofileantimalware.csv';
select 'copy ' || 'agentinstalleragentversioncontrols' as action;
copy agentinstalleragentversioncontrols FROM 'D:\Backup\flatfile\agentinstalleragentversioncontrols.csv';
select 'copy ' || 'hosts' as action;
copy hosts FROM 'D:\Backup\flatfile\hosts.csv';
select 'copy ' || 'tenanthistory' as action;
copy tenanthistory FROM 'D:\Backup\flatfile\tenanthistory.csv';
select 'copy ' || 'payloadfilter2metadataoverrides' as action;
copy payloadfilter2metadataoverrides FROM 'D:\Backup\flatfile\payloadfilter2metadataoverrides.csv';
select 'copy ' || 'integrityrulemetadataoverrides' as action;
copy integrityrulemetadataoverrides FROM 'D:\Backup\flatfile\integrityrulemetadataoverrides.csv';
select 'copy ' || 'tenantdbusage' as action;
copy tenantdbusage FROM 'D:\Backup\flatfile\tenantdbusage.csv';
select 'copy ' || 'awsconnectorsyncschedules' as action;
copy awsconnectorsyncschedules FROM 'D:\Backup\flatfile\awsconnectorsyncschedules.csv';
select 'copy ' || 'devicecontroltenanthostusages' as action;
copy devicecontroltenanthostusages FROM 'D:\Backup\flatfile\devicecontroltenanthostusages.csv';
select 'copy ' || 'networkhosts' as action;
copy networkhosts FROM 'D:\Backup\flatfile\networkhosts.csv';
select 'copy ' || 'tenantdatabaseserver' as action;
copy tenantdatabaseserver FROM 'D:\Backup\flatfile\tenantdatabaseserver.csv';
select 'copy ' || 'tpmlogs' as action;
copy tpmlogs FROM 'D:\Backup\flatfile\tpmlogs.csv';
select 'copy ' || 'awsconnectormigrationtasks' as action;
copy awsconnectormigrationtasks FROM 'D:\Backup\flatfile\awsconnectormigrationtasks.csv';
select 'copy ' || 'tenanthostusage' as action;
copy tenanthostusage FROM 'D:\Backup\flatfile\tenanthostusage.csv';
select 'copy ' || 'connectorhostgroups' as action;
copy connectorhostgroups FROM 'D:\Backup\flatfile\connectorhostgroups.csv';
select 'copy ' || 'securityprofilepacketfilterinterfacetypes' as action;
copy securityprofilepacketfilterinterfacetypes FROM 'D:\Backup\flatfile\securityprofilepacketfilterinterfacetypes.csv';
select 'copy ' || 'counterloginspection' as action;
copy counterloginspection FROM 'D:\Backup\flatfile\counterloginspection.csv';
select 'copy ' || 'virtualesx' as action;
copy virtualesx FROM 'D:\Backup\flatfile\virtualesx.csv';
select 'copy ' || 'commonobjectmigrationtasks' as action;
copy commonobjectmigrationtasks FROM 'D:\Backup\flatfile\commonobjectmigrationtasks.csv';
select 'copy ' || 'tenanthostusageaggregate' as action;
copy tenanthostusageaggregate FROM 'D:\Backup\flatfile\tenanthostusageaggregate.csv';
select 'copy ' || 'counterloginspectiondescriptions' as action;
copy counterloginspectiondescriptions FROM 'D:\Backup\flatfile\counterloginspectiondescriptions.csv';
select 'copy ' || 'activationcodes' as action;
copy activationcodes FROM 'D:\Backup\flatfile\activationcodes.csv';
select 'copy ' || 'interfacetypes' as action;
copy interfacetypes FROM 'D:\Backup\flatfile\interfacetypes.csv';
select 'copy ' || 'networksecurityprofiles' as action;
copy networksecurityprofiles FROM 'D:\Backup\flatfile\networksecurityprofiles.csv';
select 'copy ' || 'loginspectiondecoders' as action;
copy loginspectiondecoders FROM 'D:\Backup\flatfile\loginspectiondecoders.csv';
select 'copy ' || 'vcenterclusterinfofullsynctasks' as action;
copy vcenterclusterinfofullsynctasks FROM 'D:\Backup\flatfile\vcenterclusterinfofullsynctasks.csv';
select 'copy ' || 'tenantstats' as action;
copy tenantstats FROM 'D:\Backup\flatfile\tenantstats.csv';
select 'copy ' || 'administratorroles' as action;
copy administratorroles FROM 'D:\Backup\flatfile\administratorroles.csv';
select 'copy ' || 'virtualvm' as action;
copy virtualvm FROM 'D:\Backup\flatfile\virtualvm.csv';
select 'copy ' || 'securityprofilepayloadfilter2interfacetypes' as action;
copy securityprofilepayloadfilter2interfacetypes FROM 'D:\Backup\flatfile\securityprofilepayloadfilter2interfacetypes.csv';
select 'copy ' || 'actrustrules' as action;
copy actrustrules FROM 'D:\Backup\flatfile\actrustrules.csv';
select 'copy ' || 'virtuals' as action;
copy virtuals FROM 'D:\Backup\flatfile\virtuals.csv';
select 'copy ' || 'jvmstats' as action;
copy jvmstats FROM 'D:\Backup\flatfile\jvmstats.csv';
select 'copy ' || 'loginspectionevents' as action;
copy loginspectionevents FROM 'D:\Backup\flatfile\loginspectionevents.csv';
select 'copy ' || 'actrustrulesets' as action;
copy actrustrulesets FROM 'D:\Backup\flatfile\actrustrulesets.csv';
select 'copy ' || 'administratorsettings' as action;
copy administratorsettings FROM 'D:\Backup\flatfile\administratorsettings.csv';
select 'copy ' || 'vcenterclusterinfopartialsynctasks' as action;
copy vcenterclusterinfopartialsynctasks FROM 'D:\Backup\flatfile\vcenterclusterinfopartialsynctasks.csv';
select 'copy ' || 'vmotionstates' as action;
copy vmotionstates FROM 'D:\Backup\flatfile\vmotionstates.csv';
select 'copy ' || 'lock3s' as action;
copy lock3s FROM 'D:\Backup\flatfile\lock3s.csv';
select 'copy ' || 'packetfilters' as action;
copy packetfilters FROM 'D:\Backup\flatfile\packetfilters.csv';
select 'copy ' || 'eventdatabaseservers' as action;
copy eventdatabaseservers FROM 'D:\Backup\flatfile\eventdatabaseservers.csv';
select 'copy ' || 'saphosts' as action;
copy saphosts FROM 'D:\Backup\flatfile\saphosts.csv';
select 'copy ' || 'actrustrulemap' as action;
copy actrustrulemap FROM 'D:\Backup\flatfile\actrustrulemap.csv';
select 'copy ' || 'loginspectionhosts' as action;
copy loginspectionhosts FROM 'D:\Backup\flatfile\loginspectionhosts.csv';
select 'copy ' || 'alert2antimalwares' as action;
copy alert2antimalwares FROM 'D:\Backup\flatfile\alert2antimalwares.csv';
select 'copy ' || 'vulnerabilityshieldupdates' as action;
copy vulnerabilityshieldupdates FROM 'D:\Backup\flatfile\vulnerabilityshieldupdates.csv';
select 'copy ' || 'sensorindicatorevents' as action;
copy sensorindicatorevents FROM 'D:\Backup\flatfile\sensorindicatorevents.csv';
select 'copy ' || 'agentinstallers' as action;
copy agentinstallers FROM 'D:\Backup\flatfile\agentinstallers.csv';
select 'copy ' || 'googleprojects' as action;
copy googleprojects FROM 'D:\Backup\flatfile\googleprojects.csv';
select 'copy ' || 'managerjobs' as action;
copy managerjobs FROM 'D:\Backup\flatfile\managerjobs.csv';
select 'copy ' || 'agentdownloadsegments' as action;
copy agentdownloadsegments FROM 'D:\Backup\flatfile\agentdownloadsegments.csv';
select 'copy ' || 'softwareupdateentrys' as action;
copy softwareupdateentrys FROM 'D:\Backup\flatfile\softwareupdateentrys.csv';
select 'copy ' || 'changelogs' as action;
copy changelogs FROM 'D:\Backup\flatfile\changelogs.csv';
select 'copy ' || 'alerttypes' as action;
copy alerttypes FROM 'D:\Backup\flatfile\alerttypes.csv';
select 'copy ' || 'sapsecurityprofiles' as action;
copy sapsecurityprofiles FROM 'D:\Backup\flatfile\sapsecurityprofiles.csv';
select 'copy ' || 'loginspectionrules' as action;
copy loginspectionrules FROM 'D:\Backup\flatfile\loginspectionrules.csv';
select 'copy ' || 'awsglobalcrossaccountroles' as action;
copy awsglobalcrossaccountroles FROM 'D:\Backup\flatfile\awsglobalcrossaccountroles.csv';
select 'copy ' || 'amazonaccount2s' as action;
copy amazonaccount2s FROM 'D:\Backup\flatfile\amazonaccount2s.csv';
select 'copy ' || 'countermatchantimalwarewebreps' as action;
copy countermatchantimalwarewebreps FROM 'D:\Backup\flatfile\countermatchantimalwarewebreps.csv';
select 'copy ' || 'backupfiles' as action;
copy backupfiles FROM 'D:\Backup\flatfile\backupfiles.csv';
select 'copy ' || 'managerhistory2s' as action;
copy managerhistory2s FROM 'D:\Backup\flatfile\managerhistory2s.csv';
select 'copy ' || 'administrators' as action;
copy administrators FROM 'D:\Backup\flatfile\administrators.csv';
select 'copy ' || 'loginspectionsecurityprofiles' as action;
copy loginspectionsecurityprofiles FROM 'D:\Backup\flatfile\loginspectionsecurityprofiles.csv';
select 'copy ' || 'availablesystemversions' as action;
copy availablesystemversions FROM 'D:\Backup\flatfile\availablesystemversions.csv';
select 'copy ' || 'googlecomputeinstances' as action;
copy googlecomputeinstances FROM 'D:\Backup\flatfile\googlecomputeinstances.csv';
select 'copy ' || 'saptenanthostusages' as action;
copy saptenanthostusages FROM 'D:\Backup\flatfile\saptenanthostusages.csv';
select 'copy ' || 'managermessages' as action;
copy managermessages FROM 'D:\Backup\flatfile\managermessages.csv';
select 'copy ' || 'agentevents' as action;
copy agentevents FROM 'D:\Backup\flatfile\agentevents.csv';
select 'copy ' || 'eventbasedtaskconditions' as action;
copy eventbasedtaskconditions FROM 'D:\Backup\flatfile\eventbasedtaskconditions.csv';
select 'copy ' || 'certifiedfingerprints' as action;
copy certifiedfingerprints FROM 'D:\Backup\flatfile\certifiedfingerprints.csv';
select 'copy ' || 'hostpayloadfilter2s' as action;
copy hostpayloadfilter2s FROM 'D:\Backup\flatfile\hostpayloadfilter2s.csv';
select 'copy ' || 'appcontrolevents' as action;
copy appcontrolevents FROM 'D:\Backup\flatfile\appcontrolevents.csv';
select 'copy ' || 'packetloghistory' as action;
copy packetloghistory FROM 'D:\Backup\flatfile\packetloghistory.csv';
select 'copy ' || 'administratorrolehostgroups' as action;
copy administratorrolehostgroups FROM 'D:\Backup\flatfile\administratorrolehostgroups.csv';
select 'copy ' || 'systemeventhistory' as action;
copy systemeventhistory FROM 'D:\Backup\flatfile\systemeventhistory.csv';
select 'copy ' || 'connectorhosts' as action;
copy connectorhosts FROM 'D:\Backup\flatfile\connectorhosts.csv';
select 'copy ' || 'loginspectiontenanthostusages' as action;
copy loginspectiontenanthostusages FROM 'D:\Backup\flatfile\loginspectiontenanthostusages.csv';
select 'copy ' || 'checkedoutobjects' as action;
copy checkedoutobjects FROM 'D:\Backup\flatfile\checkedoutobjects.csv';
select 'copy ' || 'systemevents' as action;
copy systemevents FROM 'D:\Backup\flatfile\systemevents.csv';
select 'copy ' || 'eventbasedtaskactions' as action;
copy eventbasedtaskactions FROM 'D:\Backup\flatfile\eventbasedtaskactions.csv';
select 'copy ' || 'icaptenanthostusages' as action;
copy icaptenanthostusages FROM 'D:\Backup\flatfile\icaptenanthostusages.csv';
select 'copy ' || 'upgradetasks' as action;
copy upgradetasks FROM 'D:\Backup\flatfile\upgradetasks.csv';
select 'copy ' || 'clientsessions' as action;
copy clientsessions FROM 'D:\Backup\flatfile\clientsessions.csv';
select 'copy ' || 'administratorrolerights' as action;
copy administratorrolerights FROM 'D:\Backup\flatfile\administratorrolerights.csv';
select 'copy ' || 'appcontrolhosts' as action;
copy appcontrolhosts FROM 'D:\Backup\flatfile\appcontrolhosts.csv';
select 'copy ' || 'agentreportedconnectorhostinfos' as action;
copy agentreportedconnectorhostinfos FROM 'D:\Backup\flatfile\agentreportedconnectorhostinfos.csv';
select 'copy ' || 'payloadfilter2s' as action;
copy payloadfilter2s FROM 'D:\Backup\flatfile\payloadfilter2s.csv';
select 'copy ' || 'loginspectiondecodermetadatas' as action;
copy loginspectiondecodermetadatas FROM 'D:\Backup\flatfile\loginspectiondecodermetadatas.csv';
select 'copy ' || 'clouds' as action;
copy clouds FROM 'D:\Backup\flatfile\clouds.csv';
select 'copy ' || 'recentcomments' as action;
copy recentcomments FROM 'D:\Backup\flatfile\recentcomments.csv';
select 'copy ' || 'filebackuptaskfilepaths' as action;
copy filebackuptaskfilepaths FROM 'D:\Backup\flatfile\filebackuptaskfilepaths.csv';
select 'copy ' || 'cloudinstances' as action;
copy cloudinstances FROM 'D:\Backup\flatfile\cloudinstances.csv';
select 'copy ' || 'googlecomputeinstancetags' as action;
copy googlecomputeinstancetags FROM 'D:\Backup\flatfile\googlecomputeinstancetags.csv';
select 'copy ' || 'agentinstallerplugins' as action;
copy agentinstallerplugins FROM 'D:\Backup\flatfile\agentinstallerplugins.csv';
select 'copy ' || 'loginspectioneventhistory' as action;
copy loginspectioneventhistory FROM 'D:\Backup\flatfile\loginspectioneventhistory.csv';
select 'copy ' || 'appcontrolsecurityprofiles' as action;
copy appcontrolsecurityprofiles FROM 'D:\Backup\flatfile\appcontrolsecurityprofiles.csv';
select 'copy ' || 'comments' as action;
copy comments FROM 'D:\Backup\flatfile\comments.csv';
select 'copy ' || 'hostinterfaceips' as action;
copy hostinterfaceips FROM 'D:\Backup\flatfile\hostinterfaceips.csv';
select 'copy ' || 'saveddashboards' as action;
copy saveddashboards FROM 'D:\Backup\flatfile\saveddashboards.csv';
select 'copy ' || 'azureconnectormigrationtasks' as action;
copy azureconnectormigrationtasks FROM 'D:\Backup\flatfile\azureconnectormigrationtasks.csv';
select 'copy ' || 'payloadloghistory' as action;
copy payloadloghistory FROM 'D:\Backup\flatfile\payloadloghistory.csv';
select 'copy ' || 'agentinstallersegments' as action;
copy agentinstallersegments FROM 'D:\Backup\flatfile\agentinstallersegments.csv';
select 'copy ' || 'components' as action;
copy components FROM 'D:\Backup\flatfile\components.csv';
select 'copy ' || 'googlecomputeinstancelabels' as action;
copy googlecomputeinstancelabels FROM 'D:\Backup\flatfile\googlecomputeinstancelabels.csv';
select 'copy ' || 'appcontroltenanthostusages' as action;
copy appcontroltenanthostusages FROM 'D:\Backup\flatfile\appcontroltenanthostusages.csv';
select 'copy ' || 'gcpconnectormigrationtasks' as action;
copy gcpconnectormigrationtasks FROM 'D:\Backup\flatfile\gcpconnectormigrationtasks.csv';
select 'copy ' || 'hostmetadataattributes' as action;
copy hostmetadataattributes FROM 'D:\Backup\flatfile\hostmetadataattributes.csv';
select 'copy ' || 'securityprofilesystemsettings' as action;
copy securityprofilesystemsettings FROM 'D:\Backup\flatfile\securityprofilesystemsettings.csv';
select 'copy ' || 'devicecontrolevents' as action;
copy devicecontrolevents FROM 'D:\Backup\flatfile\devicecontrolevents.csv';
select 'copy ' || 'loginspectionrulemetadatas' as action;
copy loginspectionrulemetadatas FROM 'D:\Backup\flatfile\loginspectionrulemetadatas.csv';
select 'copy ' || 'detectionexpressions' as action;
copy detectionexpressions FROM 'D:\Backup\flatfile\detectionexpressions.csv';
select 'copy ' || 'alert2s' as action;
copy alert2s FROM 'D:\Backup\flatfile\alert2s.csv';
select 'copy ' || 'devicecontroleventhistory' as action;
copy devicecontroleventhistory FROM 'D:\Backup\flatfile\devicecontroleventhistory.csv';
select 'copy ' || 'connectorhostmetadatas' as action;
copy connectorhostmetadatas FROM 'D:\Backup\flatfile\connectorhostmetadatas.csv';
select 'copy ' || 'hostscanports' as action;
copy hostscanports FROM 'D:\Backup\flatfile\hostscanports.csv';
select 'copy ' || 'securityprofileconnectiontypes' as action;
copy securityprofileconnectiontypes FROM 'D:\Backup\flatfile\securityprofileconnectiontypes.csv';
select 'copy ' || 'loginspectionruleoverrides' as action;
copy loginspectionruleoverrides FROM 'D:\Backup\flatfile\loginspectionruleoverrides.csv';
select 'copy ' || 'detectionruletoindexs' as action;
copy detectionruletoindexs FROM 'D:\Backup\flatfile\detectionruletoindexs.csv';
select 'copy ' || 'inventorymetadatas' as action;
copy inventorymetadatas FROM 'D:\Backup\flatfile\inventorymetadatas.csv';
select 'copy ' || 'serverloghistory' as action;
copy serverloghistory FROM 'D:\Backup\flatfile\serverloghistory.csv';
select 'copy ' || 'amazonregions' as action;
copy amazonregions FROM 'D:\Backup\flatfile\amazonregions.csv';
select 'copy ' || 'usbdevices' as action;
copy usbdevices FROM 'D:\Backup\flatfile\usbdevices.csv';
select 'copy ' || 'directories' as action;
copy directories FROM 'D:\Backup\flatfile\directories.csv';
select 'copy ' || 'alertupdateevents' as action;
copy alertupdateevents FROM 'D:\Backup\flatfile\alertupdateevents.csv';
select 'copy ' || 'connectorhostgcpdatas' as action;
copy connectorhostgcpdatas FROM 'D:\Backup\flatfile\connectorhostgcpdatas.csv';
select 'copy ' || 'relaylistupdates' as action;
copy relaylistupdates FROM 'D:\Backup\flatfile\relaylistupdates.csv';
select 'copy ' || 'acrulesets' as action;
copy acrulesets FROM 'D:\Backup\flatfile\acrulesets.csv';
select 'copy ' || 'securityprofileconnectiontypeportoverrides' as action;
copy securityprofileconnectiontypeportoverrides FROM 'D:\Backup\flatfile\securityprofileconnectiontypeportoverrides.csv';
select 'copy ' || 'autotagrules' as action;
copy autotagrules FROM 'D:\Backup\flatfile\autotagrules.csv';
select 'copy ' || 'discoveryjobs' as action;
copy discoveryjobs FROM 'D:\Backup\flatfile\discoveryjobs.csv';
select 'copy ' || 'apievents' as action;
copy apievents FROM 'D:\Backup\flatfile\apievents.csv';
select 'copy ' || 'hostdevicerules' as action;
copy hostdevicerules FROM 'D:\Backup\flatfile\hostdevicerules.csv';
select 'copy ' || 'securityprofileloginspectionrules' as action;
copy securityprofileloginspectionrules FROM 'D:\Backup\flatfile\securityprofileloginspectionrules.csv';
select 'copy ' || 'acinventorychanges' as action;
copy acinventorychanges FROM 'D:\Backup\flatfile\acinventorychanges.csv';
select 'copy ' || 'scheduledtaskadministrators' as action;
copy scheduledtaskadministrators FROM 'D:\Backup\flatfile\scheduledtaskadministrators.csv';
select 'copy ' || 'donotdiscoverips' as action;
copy donotdiscoverips FROM 'D:\Backup\flatfile\donotdiscoverips.csv';
select 'copy ' || 'defaulttenantproperties' as action;
copy defaulttenantproperties FROM 'D:\Backup\flatfile\defaulttenantproperties.csv';
select 'copy ' || 'hostupgraderecords' as action;
copy hostupgraderecords FROM 'D:\Backup\flatfile\hostupgraderecords.csv';
select 'copy ' || 'dsmcredentials' as action;
copy dsmcredentials FROM 'D:\Backup\flatfile\dsmcredentials.csv';
select 'copy ' || 'securityprofilestatefulfilters' as action;
copy securityprofilestatefulfilters FROM 'D:\Backup\flatfile\securityprofilestatefulfilters.csv';
select 'copy ' || 'securityprofiledevicerules' as action;
copy securityprofiledevicerules FROM 'D:\Backup\flatfile\securityprofiledevicerules.csv';
select 'copy ' || 'clientsessioninfos' as action;
copy clientsessioninfos FROM 'D:\Backup\flatfile\clientsessioninfos.csv';
select 'copy ' || 'hostloginspectionrules' as action;
copy hostloginspectionrules FROM 'D:\Backup\flatfile\hostloginspectionrules.csv';
select 'copy ' || 'newsfeedentries' as action;
copy newsfeedentries FROM 'D:\Backup\flatfile\newsfeedentries.csv';
select 'copy ' || 'appcontrolblockalerts' as action;
copy appcontrolblockalerts FROM 'D:\Backup\flatfile\appcontrolblockalerts.csv';
select 'copy ' || 'scheduledtaskcontactss' as action;
copy scheduledtaskcontactss FROM 'D:\Backup\flatfile\scheduledtaskcontactss.csv';
select 'copy ' || 'emails' as action;
copy emails FROM 'D:\Backup\flatfile\emails.csv';
select 'copy ' || 'tenantfeaturestates' as action;
copy tenantfeaturestates FROM 'D:\Backup\flatfile\tenantfeaturestates.csv';
select 'copy ' || 'cloudinstancemetadatas' as action;
copy cloudinstancemetadatas FROM 'D:\Backup\flatfile\cloudinstancemetadatas.csv';
select 'copy ' || 'helparticles' as action;
copy helparticles FROM 'D:\Backup\flatfile\helparticles.csv';
select 'copy ' || 'samlidentityproviders' as action;
copy samlidentityproviders FROM 'D:\Backup\flatfile\samlidentityproviders.csv';
select 'copy ' || 'appcontroleventhistory' as action;
copy appcontroleventhistory FROM 'D:\Backup\flatfile\appcontroleventhistory.csv';
select 'copy ' || 'alert2loginspectionrules' as action;
copy alert2loginspectionrules FROM 'D:\Backup\flatfile\alert2loginspectionrules.csv';
select 'copy ' || 'virtualesxcustomattributes' as action;
copy virtualesxcustomattributes FROM 'D:\Backup\flatfile\virtualesxcustomattributes.csv';
select 'copy ' || 'localtotpdata' as action;
copy localtotpdata FROM 'D:\Backup\flatfile\localtotpdata.csv';
select 'copy ' || 'sslhostconfigurations' as action;
copy sslhostconfigurations FROM 'D:\Backup\flatfile\sslhostconfigurations.csv';
select 'copy ' || 'samlsignin3s' as action;
copy samlsignin3s FROM 'D:\Backup\flatfile\samlsignin3s.csv';
select 'copy ' || 'contacts' as action;
copy contacts FROM 'D:\Backup\flatfile\contacts.csv';
select 'copy ' || 'hostassetimportance' as action;
copy hostassetimportance FROM 'D:\Backup\flatfile\hostassetimportance.csv';
select 'copy ' || 'virtualvmcustomattributes' as action;
copy virtualvmcustomattributes FROM 'D:\Backup\flatfile\virtualvmcustomattributes.csv';
select 'copy ' || 'schedulerruntime' as action;
copy schedulerruntime FROM 'D:\Backup\flatfile\schedulerruntime.csv';
select 'copy ' || 'activehosterrors' as action;
copy activehosterrors FROM 'D:\Backup\flatfile\activehosterrors.csv';
select 'copy ' || 'countermatchloginspections' as action;
copy countermatchloginspections FROM 'D:\Backup\flatfile\countermatchloginspections.csv';
select 'copy ' || 'hostbridges' as action;
copy hostbridges FROM 'D:\Backup\flatfile\hostbridges.csv';
select 'copy ' || 'connectiontypemetadataoverrides' as action;
copy connectiontypemetadataoverrides FROM 'D:\Backup\flatfile\connectiontypemetadataoverrides.csv';
select 'copy ' || 'virtualappliancesvmupgradetask' as action;
copy virtualappliancesvmupgradetask FROM 'D:\Backup\flatfile\virtualappliancesvmupgradetask.csv';
select 'copy ' || 'antimalwareevents' as action;
copy antimalwareevents FROM 'D:\Backup\flatfile\antimalwareevents.csv';
select 'copy ' || 'hostgroups' as action;
copy hostgroups FROM 'D:\Backup\flatfile\hostgroups.csv';
select 'copy ' || 'awshostgroups' as action;
copy awshostgroups FROM 'D:\Backup\flatfile\awshostgroups.csv';
select 'copy ' || 'managernodes' as action;
copy managernodes FROM 'D:\Backup\flatfile\managernodes.csv';
select 'copy ' || 'loginspectionrulemetadataoverrides' as action;
copy loginspectionrulemetadataoverrides FROM 'D:\Backup\flatfile\loginspectionrulemetadataoverrides.csv';
select 'copy ' || 'acrules' as action;
copy acrules FROM 'D:\Backup\flatfile\acrules.csv';
select 'copy ' || 'antimalwarehosts' as action;
copy antimalwarehosts FROM 'D:\Backup\flatfile\antimalwarehosts.csv';
select 'copy ' || 'administratorrolehosts' as action;
copy administratorrolehosts FROM 'D:\Backup\flatfile\administratorrolehosts.csv';
select 'copy ' || 'hoststatuslog' as action;
copy hoststatuslog FROM 'D:\Backup\flatfile\hoststatuslog.csv';
select 'copy ' || 'counterwatch2s' as action;
copy counterwatch2s FROM 'D:\Backup\flatfile\counterwatch2s.csv';
select 'copy ' || 'modulestatuses' as action;
copy modulestatuses FROM 'D:\Backup\flatfile\modulestatuses.csv';
select 'copy ' || 'iplists' as action;
copy iplists FROM 'D:\Backup\flatfile\iplists.csv';
select 'copy ' || 'awsconnectorlocks' as action;
copy awsconnectorlocks FROM 'D:\Backup\flatfile\awsconnectorlocks.csv';
select 'copy ' || 'acinventoryitems' as action;
copy acinventoryitems FROM 'D:\Backup\flatfile\acinventoryitems.csv';
select 'copy ' || 'containercontrolevents' as action;
copy containercontrolevents FROM 'D:\Backup\flatfile\containercontrolevents.csv';
select 'copy ' || 'antimalwarequarantinedfile' as action;
copy antimalwarequarantinedfile FROM 'D:\Backup\flatfile\antimalwarequarantinedfile.csv';
select 'copy ' || 'agentdownloads' as action;
copy agentdownloads FROM 'D:\Backup\flatfile\agentdownloads.csv';
select 'copy ' || 'connectiontypes' as action;
copy connectiontypes FROM 'D:\Backup\flatfile\connectiontypes.csv';
select 'copy ' || 'nsxsecuritygroups' as action;
copy nsxsecuritygroups FROM 'D:\Backup\flatfile\nsxsecuritygroups.csv';
select 'copy ' || 'performanceprofiles' as action;
copy performanceprofiles FROM 'D:\Backup\flatfile\performanceprofiles.csv';
select 'copy ' || 'samlidentityprovidercertificates' as action;
copy samlidentityprovidercertificates FROM 'D:\Backup\flatfile\samlidentityprovidercertificates.csv';
select 'copy ' || 'baselineentitys' as action;
copy baselineentitys FROM 'D:\Backup\flatfile\baselineentitys.csv';
select 'copy ' || 'antimalwaresecurityprofiles' as action;
copy antimalwaresecurityprofiles FROM 'D:\Backup\flatfile\antimalwaresecurityprofiles.csv';
select 'copy ' || 'containercontrolhosts' as action;
copy containercontrolhosts FROM 'D:\Backup\flatfile\containercontrolhosts.csv';
select 'copy ' || 'agentqueuedcommands' as action;
copy agentqueuedcommands FROM 'D:\Backup\flatfile\agentqueuedcommands.csv';
select 'copy ' || 'hostinterfaceippacketfilters' as action;
copy hostinterfaceippacketfilters FROM 'D:\Backup\flatfile\hostinterfaceippacketfilters.csv';
select 'copy ' || 'performanceprofiledatas' as action;
copy performanceprofiledatas FROM 'D:\Backup\flatfile\performanceprofiledatas.csv';
select 'copy ' || 'counter3s' as action;
copy counter3s FROM 'D:\Backup\flatfile\counter3s.csv';
select 'copy ' || 'pluginsettings' as action;
copy pluginsettings FROM 'D:\Backup\flatfile\pluginsettings.csv';
select 'copy ' || 'systemeventscache' as action;
copy systemeventscache FROM 'D:\Backup\flatfile\systemeventscache.csv';
select 'copy ' || 'counterintegritys' as action;
copy counterintegritys FROM 'D:\Backup\flatfile\counterintegritys.csv';
select 'copy ' || 'counter3ips' as action;
copy counter3ips FROM 'D:\Backup\flatfile\counter3ips.csv';
select 'copy ' || 'counterintegritykeys' as action;
copy counterintegritykeys FROM 'D:\Backup\flatfile\counterintegritykeys.csv';
select 'copy ' || 'antimalwarespywareitems' as action;
copy antimalwarespywareitems FROM 'D:\Backup\flatfile\antimalwarespywareitems.csv';
select 'copy ' || 'alert2hosts' as action;
copy alert2hosts FROM 'D:\Backup\flatfile\alert2hosts.csv';
select 'copy ' || 'counter3ports' as action;
copy counter3ports FROM 'D:\Backup\flatfile\counter3ports.csv';
select 'copy ' || 'portlists' as action;
copy portlists FROM 'D:\Backup\flatfile\portlists.csv';
select 'copy ' || 'registryscanners' as action;
copy registryscanners FROM 'D:\Backup\flatfile\registryscanners.csv';
select 'copy ' || 'hostinterfacepacketfilters' as action;
copy hostinterfacepacketfilters FROM 'D:\Backup\flatfile\hostinterfacepacketfilters.csv';
select 'copy ' || 'securityprofiles' as action;
copy securityprofiles FROM 'D:\Backup\flatfile\securityprofiles.csv';
select 'copy ' || 'maclists' as action;
copy maclists FROM 'D:\Backup\flatfile\maclists.csv';
select 'copy ' || 'systemeventscache2' as action;
copy systemeventscache2 FROM 'D:\Backup\flatfile\systemeventscache2.csv';
select 'copy ' || 'antimalwaretenanthostusages' as action;
copy antimalwaretenanthostusages FROM 'D:\Backup\flatfile\antimalwaretenanthostusages.csv';
select 'copy ' || 'integrityevents' as action;
copy integrityevents FROM 'D:\Backup\flatfile\integrityevents.csv';
select 'copy ' || 'postprocessor' as action;
copy postprocessor FROM 'D:\Backup\flatfile\postprocessor.csv';
select 'copy ' || 'containercontrolsecurityprofiles' as action;
copy containercontrolsecurityprofiles FROM 'D:\Backup\flatfile\containercontrolsecurityprofiles.csv';
select 'copy ' || 'amazonsubnets' as action;
copy amazonsubnets FROM 'D:\Backup\flatfile\amazonsubnets.csv';
select 'copy ' || 'packeterrors' as action;
copy packeterrors FROM 'D:\Backup\flatfile\packeterrors.csv';
select 'copy ' || 'amazonsecuritygroup2s' as action;
copy amazonsecuritygroup2s FROM 'D:\Backup\flatfile\amazonsecuritygroup2s.csv';
select 'copy ' || 'hostinterfacepayloadfilter2s' as action;
copy hostinterfacepayloadfilter2s FROM 'D:\Backup\flatfile\hostinterfacepayloadfilter2s.csv';
select 'copy ' || 'serverlogs' as action;
copy serverlogs FROM 'D:\Backup\flatfile\serverlogs.csv';
select 'copy ' || 'proxies' as action;
copy proxies FROM 'D:\Backup\flatfile\proxies.csv';
select 'copy ' || 'integrityhosts' as action;
copy integrityhosts FROM 'D:\Backup\flatfile\integrityhosts.csv';
select 'copy ' || 'counterantimalware' as action;
copy counterantimalware FROM 'D:\Backup\flatfile\counterantimalware.csv';
select 'copy ' || 'packetfiltertenanthostusages' as action;
copy packetfiltertenanthostusages FROM 'D:\Backup\flatfile\packetfiltertenanthostusages.csv';
select 'copy ' || 'counterantimalwarescanstatus' as action;
copy counterantimalwarescanstatus FROM 'D:\Backup\flatfile\counterantimalwarescanstatus.csv';
select 'copy ' || 'countermatch2s' as action;
copy countermatch2s FROM 'D:\Backup\flatfile\countermatch2s.csv';
select 'copy ' || 'amazondirectories' as action;
copy amazondirectories FROM 'D:\Backup\flatfile\amazondirectories.csv';
select 'copy ' || 'containercontroltenanthostusages' as action;
copy containercontroltenanthostusages FROM 'D:\Backup\flatfile\containercontroltenanthostusages.csv';
select 'copy ' || 'counterwebreputation' as action;
copy counterwebreputation FROM 'D:\Backup\flatfile\counterwebreputation.csv';
select 'copy ' || 'reporttemplatemetadatas' as action;
copy reporttemplatemetadatas FROM 'D:\Backup\flatfile\reporttemplatemetadatas.csv';
select 'copy ' || 'scandirectorylists' as action;
copy scandirectorylists FROM 'D:\Backup\flatfile\scandirectorylists.csv';
select 'copy ' || 'hostpacketfilters' as action;
copy hostpacketfilters FROM 'D:\Backup\flatfile\hostpacketfilters.csv';
select 'copy ' || 'integrityrules' as action;
copy integrityrules FROM 'D:\Backup\flatfile\integrityrules.csv';
select 'copy ' || 'filebackuptasks' as action;
copy filebackuptasks FROM 'D:\Backup\flatfile\filebackuptasks.csv';
select 'copy ' || 'packetlogs' as action;
copy packetlogs FROM 'D:\Backup\flatfile\packetlogs.csv';
select 'copy ' || 'relaylists' as action;
copy relaylists FROM 'D:\Backup\flatfile\relaylists.csv';
select 'copy ' || 'newsfeedentryadministrators' as action;
copy newsfeedentryadministrators FROM 'D:\Backup\flatfile\newsfeedentryadministrators.csv';
select 'copy ' || 'tagsettags' as action;
copy tagsettags FROM 'D:\Backup\flatfile\tagsettags.csv';
select 'copy ' || 'containercontrolimages' as action;
copy containercontrolimages FROM 'D:\Backup\flatfile\containercontrolimages.csv';
select 'copy ' || 'scanfilelists' as action;
copy scanfilelists FROM 'D:\Backup\flatfile\scanfilelists.csv';
select 'copy ' || 'integritysecurityprofiles' as action;
copy integritysecurityprofiles FROM 'D:\Backup\flatfile\integritysecurityprofiles.csv';
select 'copy ' || 'hostappliancedeployversion' as action;
copy hostappliancedeployversion FROM 'D:\Backup\flatfile\hostappliancedeployversion.csv';
select 'copy ' || 'packetlogdatas' as action;
copy packetlogdatas FROM 'D:\Backup\flatfile\packetlogdatas.csv';
select 'copy ' || 'rights' as action;
copy rights FROM 'D:\Backup\flatfile\rights.csv';
select 'copy ' || 'partitionerrors' as action;
copy partitionerrors FROM 'D:\Backup\flatfile\partitionerrors.csv';
select 'copy ' || 'scanfileextlists' as action;
copy scanfileextlists FROM 'D:\Backup\flatfile\scanfileextlists.csv';
select 'copy ' || 'tenants' as action;
copy tenants FROM 'D:\Backup\flatfile\tenants.csv';
select 'copy ' || 'payloadfilter2tenanthostusages' as action;
copy payloadfilter2tenanthostusages FROM 'D:\Backup\flatfile\payloadfilter2tenanthostusages.csv';
select 'copy ' || 'securityprofileimageactions' as action;
copy securityprofileimageactions FROM 'D:\Backup\flatfile\securityprofileimageactions.csv';
select 'copy ' || 'hostcomponents' as action;
copy hostcomponents FROM 'D:\Backup\flatfile\hostcomponents.csv';
select 'copy ' || 'rulegroups' as action;
copy rulegroups FROM 'D:\Backup\flatfile\rulegroups.csv';
select 'copy ' || 'integritytenanthostusages' as action;
copy integritytenanthostusages FROM 'D:\Backup\flatfile\integritytenanthostusages.csv';
select 'copy ' || 'packetfilteroverrides' as action;
copy packetfilteroverrides FROM 'D:\Backup\flatfile\packetfilteroverrides.csv';
select 'copy ' || 'tenantproperties' as action;
copy tenantproperties FROM 'D:\Backup\flatfile\tenantproperties.csv';
select 'copy ' || 'webreputationevents' as action;
copy webreputationevents FROM 'D:\Backup\flatfile\webreputationevents.csv';
select 'copy ' || 'uservisibilityevents' as action;
copy uservisibilityevents FROM 'D:\Backup\flatfile\uservisibilityevents.csv';
select 'copy ' || 'payloadlogs' as action;
copy payloadlogs FROM 'D:\Backup\flatfile\payloadlogs.csv';
select 'copy ' || 'hostimageactions' as action;
copy hostimageactions FROM 'D:\Backup\flatfile\hostimageactions.csv';
select 'copy ' || 'hostcomponentupdatess' as action;
copy hostcomponentupdatess FROM 'D:\Backup\flatfile\hostcomponentupdatess.csv';
select 'copy ' || 'scancachepolicyobject' as action;
copy scancachepolicyobject FROM 'D:\Backup\flatfile\scancachepolicyobject.csv';
select 'copy ' || 'cloudinstanceamazonsecuritygroup2' as action;
copy cloudinstanceamazonsecuritygroup2 FROM 'D:\Backup\flatfile\cloudinstanceamazonsecuritygroup2.csv';
select 'copy ' || 'knowngoodhashs' as action;
copy knowngoodhashs FROM 'D:\Backup\flatfile\knowngoodhashs.csv';
select 'copy ' || 'webreputationtenanthostusages' as action;
copy webreputationtenanthostusages FROM 'D:\Backup\flatfile\webreputationtenanthostusages.csv';
select 'copy ' || 'vulnerabilitylinks' as action;
copy vulnerabilitylinks FROM 'D:\Backup\flatfile\vulnerabilitylinks.csv';
select 'copy ' || 'payloadlogdatas' as action;
copy payloadlogdatas FROM 'D:\Backup\flatfile\payloadlogdatas.csv';
select 'copy ' || 'storedtesfilters' as action;
copy storedtesfilters FROM 'D:\Backup\flatfile\storedtesfilters.csv';
select 'copy ' || 'hostinterfaces' as action;
copy hostinterfaces FROM 'D:\Backup\flatfile\hostinterfaces.csv';
select 'copy ' || 'schedules' as action;
copy schedules FROM 'D:\Backup\flatfile\schedules.csv';
select 'copy ' || 'rulecontexts' as action;
copy rulecontexts FROM 'D:\Backup\flatfile\rulecontexts.csv';
select 'copy ' || 'hostvolatiles' as action;
copy hostvolatiles FROM 'D:\Backup\flatfile\hostvolatiles.csv';
select 'copy ' || 'antimalwareransomwaretargets' as action;
copy antimalwareransomwaretargets FROM 'D:\Backup\flatfile\antimalwareransomwaretargets.csv';
select 'copy ' || 'vulnerabilitysoftwares' as action;
copy vulnerabilitysoftwares FROM 'D:\Backup\flatfile\vulnerabilitysoftwares.csv';
select 'copy ' || 'todeleteknowngoodhashs' as action;
copy todeleteknowngoodhashs FROM 'D:\Backup\flatfile\todeleteknowngoodhashs.csv';
select 'copy ' || 'agentversioncontrols' as action;
copy agentversioncontrols FROM 'D:\Backup\flatfile\agentversioncontrols.csv';
select 'copy ' || 'smartfolders' as action;
copy smartfolders FROM 'D:\Backup\flatfile\smartfolders.csv';
select 'copy ' || 'antimalware' as action;
copy antimalware FROM 'D:\Backup\flatfile\antimalware.csv';
select 'copy ' || 'sslhostconfigurationhostinterfaces' as action;
copy sslhostconfigurationhostinterfaces FROM 'D:\Backup\flatfile\sslhostconfigurationhostinterfaces.csv';
select 'copy ' || 'attribute2s' as action;
copy attribute2s FROM 'D:\Backup\flatfile\attribute2s.csv';
select 'copy ' || 'cacredentials' as action;
copy cacredentials FROM 'D:\Backup\flatfile\cacredentials.csv';
select 'copy ' || 'hostmetadatas' as action;
copy hostmetadatas FROM 'D:\Backup\flatfile\hostmetadatas.csv';
select 'copy ' || 'payloadfilter2overrides' as action;
copy payloadfilter2overrides FROM 'D:\Backup\flatfile\payloadfilter2overrides.csv';
select 'copy ' || 'hostdeletedvirtualagents' as action;
copy hostdeletedvirtualagents FROM 'D:\Backup\flatfile\hostdeletedvirtualagents.csv';
select 'copy ' || 'administratorpasswordhistory' as action;
copy administratorpasswordhistory FROM 'D:\Backup\flatfile\administratorpasswordhistory.csv';
select 'copy ' || 'softwares' as action;
copy softwares FROM 'D:\Backup\flatfile\softwares.csv';
select 'copy ' || 'hostintegrityrules' as action;
copy hostintegrityrules FROM 'D:\Backup\flatfile\hostintegrityrules.csv';
select 'copy ' || 'hostmovetasks' as action;
copy hostmovetasks FROM 'D:\Backup\flatfile\hostmovetasks.csv';
select 'copy ' || 'sslcredentials' as action;
copy sslcredentials FROM 'D:\Backup\flatfile\sslcredentials.csv';
select 'copy ' || 'relayinfos' as action;
copy relayinfos FROM 'D:\Backup\flatfile\relayinfos.csv';
select 'copy ' || 'hostmetadatagroups' as action;
copy hostmetadatagroups FROM 'D:\Backup\flatfile\hostmetadatagroups.csv';
select 'copy ' || 'suspiciousfilesubmission' as action;
copy suspiciousfilesubmission FROM 'D:\Backup\flatfile\suspiciousfilesubmission.csv';
select 'copy ' || 'managernodeupgraderecords' as action;
copy managernodeupgraderecords FROM 'D:\Backup\flatfile\managernodeupgraderecords.csv';
select 'copy ' || 'administratorrolesecurityprofiles' as action;
copy administratorrolesecurityprofiles FROM 'D:\Backup\flatfile\administratorrolesecurityprofiles.csv';
select 'copy ' || 'statefulfilters' as action;
copy statefulfilters FROM 'D:\Backup\flatfile\statefulfilters.csv';
SHOW client_encoding;
SET CLIENT_ENCODING TO 'utf8';
select 'copy ' || 'entitys' as action;
copy entitys FROM 'D:\Backup\flatfile\entitys.csv';
select 'copy ' || 'vulnerabilities' as action;
copy vulnerabilities FROM 'D:\Backup\flatfile\vulnerabilities.csv';
select 'copy ' || 'detectionrules' as action;
copy detectionrules FROM 'D:\Backup\flatfile\detectionrules.csv';
